service: unit-test-simple
custom:
  bucket: ${param:bucket, "serverless-stack-deployments"}
  pythonRequirements:
    dockerizePip: non-linux
  runtime: ${param:runtime, "python3.9"}

provider:
  deploymentBucket:
    name: ${opt:stage, "dev"}-${self:custom.bucket}
  name: aws
  region: ${file(setup/${opt:stage, "dev"}/${opt:stage, "dev"}.json):REGION, "sa-east-1"}

layers:
  unit_test_simple:
    name: unit-test-simple
    compatibleRuntimes:
      - ${self:custom.runtime}
    package:
      artifact: unit_test_simple.zip